name: Nouveau problème (Développeurs uniquement)
description: Un modèle de problème vierge réservé aux développeurs. Si vous n'êtes pas un développeur, n'utilisez pas ce modèle. Votre problème SERA FERMÉ si vous n'utilisez pas le modèle approprié.
body:
  - type: markdown
    attributes:
      value: |
        **Si vous n'êtes pas un développeur, n'utilisez pas ce modèle. Votre problème SERA CLOS si vous n'utilisez pas le modèle de problème approprié.**
  - type: textarea
    attributes:
      label: "Problème"
