name: Signalement de bug
description: Déposer un signalement de bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Le support technique n'a pas sa place ici. Vous ne devez déposer un problème ici que si vous pensez avoir rencontré un bug dans Azahar.
  - type: checkboxes
    attributes:
      label: Y a-t-il un problème existant à ce sujet ?
      description: Veuillez vérifier si un problème n'existe pas déjà pour le bug que vous avez rencontré.
      options:
      - label: J'ai recherché les problèmes existants
        required: true
  - type: input
    attributes:
      label: Version(s) affectée(s)
      description: Listez les versions affectées auxquelles ce problème s'applique.
      placeholder: 1234
    validations:
      required: true
  - type: textarea
    id: issue-desc
    attributes:
      label: Description du problème
      description: Une brève description du problème rencontré, accompagnée d'images et/ou de vidéos.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A brief description of how it is expected to work along with any images and/or videos.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Étapes de la reproduction
      description: Une brève explication de la manière de reproduire ce problème. Si possible, fournir un fichier de sauvegarde pour aider à reproduire le problème.
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Fichier journal
      description: Un fichier journal aidera nos développeurs à mieux diagnostiquer et résoudre le problème.
    validations:
      required: true
  - type: textarea
    id: system-config
    attributes:
      label: Configuration du système
      description: Informations sur votre système. Si vous utilisez Linux, indiquez si vous utilisez Flatpak ou AppImage.
        CPU: Intel i5-10400 / AMD Ryzen 5 3600
        GPU/Driver: NVIDIA GeForce GTX 1060 (Driver 512.95)
        RAM: 16GB DDR4-3200
        OS: Windows 11 22H2 (Build 22621.819)
      value: |
        CPU:
        GPU/Driver:
        RAM:
        OS:
    validations:
      required: true
