blank_issues_enabled: false
contact_links:
  - name: Azahar Discord
    url: https://discord.com/invite/4ZjMpAp3M6
    about: Si vous rencontrez un problème et que vous avez besoin d'aide, ou si vous avez une question d'ordre général, essayez de la poser dans le Discord officiel dont le lien se trouve ici. *La discussion sur le piratage n'est pas autorisée.*
