name: Demande de fonctionnalité
description: Déposer une demande de fonctionnalité
labels: ["amélioration"]
body:
  - type: markdown
    attributes:
      value: Le support technique n'a pas sa place ici. Vous ne devriez déposer un problème ici que si vous demandez une fonctionnalité qui, selon vous, améliorerait Azahar.
    attributes:
      label: Y a-t-il un problème existant à ce sujet ?
      description: Veuillez vérifier si un problème n'existe pas déjà pour la fonctionnalité que vous demandez.
      options:
      - label: J'ai recherché les problèmes existants
        required: true
  - type: textarea
    id: what-feature
    attributes:
      label: Quelle fonctionnalité suggérez-vous ?
      description: Brève description de la fonctionnalité demandée.
    validations:
      required: true
  - type: textarea
    id: why-feature
    attributes:
      label: Pourquoi cette fonctionnalité serait-elle utile ?
      description: Une brève description de la raison pour laquelle cette fonctionnalité améliorerait Azahar.
    validations:
      required: true
